
//Auth actions
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAIL="REGISTER_FAIL"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOADED_USER="LOADED_USER"
export const LOGIN_FAIL="LOGIN_FAIL"
export const AUTH_ERROR="AUTH_ERROR"
export const CLEAR_ERROR="CLEAR_ERROR"
export const LOGOUT="LOGOUT"


//Alert actions
export const SET_ALERT="SET_ALERT"
export const REMOVE_ALERT="REMOVE_ALERT"

//Troops actions
export const GET_TROOPS="GET_TROOPS"
export const ADD_TROOPS="ADD_TROOPS"
export const DELETE_TROOPS="DELETE_TROOPS"
export const UPDATE_TROOPS="UPDATE_TROOPS"
export const SAVE_TROOPS="SAVE_TROOPS"
export const CLEAR_TROOPS="CLEAR_TROOPS"
export const TROOP_ERROR="TROOP_ERROR"
export const REMOVE_CURRENT_TROOP="REMOVE_CURRENT_TROOP"

//decors actions

export const GET_DECORS="GET_DECORS"
export const ADD_DECORS="ADD_DECORS"
export const DELETE_DECORS="DELETE_DECORS"
export const UPDATE_DECORS="UPDATE_DECORS"
export const SAVE_DECORS="SAVE_DECORS"
export const CLEAR_DECORS="CLEAR_DECORS"
export const DECOR_ERROR="DECOR_ERROR"
export const REMOVE_CURRENT_DECOR="REMOVE_CURRENT_DECOR"

// cakes actions

export const GET_CAKES="GET_CAKES"
export const ADD_CAKES="ADD_CAKES"
export const DELETE_CAKES="DELETE_CAKES"
export const UPDATE_CAKES="UPDATE_CAKES"
export const SAVE_CAKES="SAVE_CAKES"
export const CLEAR_CAKES="CLEAR_CAKES"
export const CAKES_ERROR="CAKES_ERROR"
export const REMOVE_CURRENT_CAKES="REMOVE_CURRENT_CAKES"

//salles actions

// export const GET_="GET_CAKES"
// export const ADD_CAKES="ADD_CAKES"
// export const DELETE_CAKES="DELETE_CAKES"
// export const UPDATE_CAKES="UPDATE_CAKES"
// export const SAVE_CAKES="SAVE_CAKES"
// export const CLEAR_CAKES="CLEAR_CAKES"
// export const CAKES_ERROR="CAKES_ERROR"
// export const REMOVE_CURRENT_CAKES="REMOVE_CURRENT_CAKES"

//Party rooms actions

export const GET_ROOMS="GET_ROOMS"
export const ADD_ROOMS="ADD_ROOMS"
export const DELETE_ROOMS="DELETE_ROOMS"
export const UPDATE_ROOMS="UPDATE_ROOMS"
export const SAVE_ROOMS="SAVE_ROOMS"
export const CLEAR_ROOMS="CLEAR_ROOMS"
export const ROOMS_ERROR="ROOMS_ERROR"
export const REMOVE_CURRENT_ROOMS="REMOVE_CURRENT_ROOMS"

// RESEVATION ACTIONS

export const GET_RESEVATION="GET_RESEVATION"
export const ADD_RESEVATION="ADD_RESEVATION"
export const DELETE_RESEVATION="DELETE_RESEVATION"
export const UPDATE_RESEVATION="UPDATE_RESEVATION"
export const SAVE_RESEVATION="SAVE_RESEVATION"
export const CLEAR_RESEVATION="CLEAR_RESEVATION"
export const RESEVATION_ERROR="RESEVATION_ERROR"
export const REMOVE_CURRENT_RESEVATION="REMOVE_CURRENT_RESEVATION"

// VEHICULE ACTIONS

export const GET_VEHICULE="GET_VEHICULE"
export const ADD_VEHICULE="ADD_VEHICULE"
export const DELETE_VEHICULE="DELETE_VEHICULE"
export const UPDATE_VEHICULE="UPDATE_VEHICULE"
export const SAVE_VEHICULE="SAVE_VEHICULE"
export const CLEAR_VEHICULE="CLEAR_VEHICULE"
export const VEHICULE_ERROR="VEHICULE_ERROR"
export const REMOVE_CURRENT_VEHICULE="REMOVE_CURRENT_VEHICULE"

